name: Deploy Pages

on:
  push:
    branches: ["main"]
  schedule:
    - cron: "0 */6 * * *"
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

env:
  HUGO_VERSION: "0.147.3" # https://github.com/google/docsy/blob/main/package.json
  DOCSY_VERSION: "v0.11.0"

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        project: ["aileron"]
    steps:
      - uses: actions/checkout@v4
      - run: |
          sudo chmod +x ./make.sh
          PROJECT="${{ matrix.project }}" ./make.sh
      - uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.project }}
          path: |
            ./content/${{ matrix.project }}/
            ./static/${{ matrix.project }}/

  merge:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/upload-artifact/merge@v4
        with:
          delete-merged: true

  hugo:
    runs-on: ubuntu-latest
    needs: merge
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
          fetch-depth: 0
      - name: Setup Pages
        id: pages
        uses: actions/configure-pages@v5
      - uses: actions/download-artifact@v4
      - run: |
          ls -la
          ls -la merged-artifacts
          cp -r merged-artifacts/* ./
      - name: install hugo
        run: |
          wget -O hugo.deb https://github.com/gohugoio/hugo/releases/download/v${HUGO_VERSION}/hugo_extended_${HUGO_VERSION}_linux-amd64.deb
          sudo dpkg -i hugo.deb
          sudo snap install dart-sass
          npm install
      - run: cd themes/docsy/ && git fetch --tags && git checkout tags/${DOCSY_VERSION}
      - run: cd themes/docsy/ && npm install
      - name: Build with Hugo
        env:
          HUGO_CACHEDIR: ${{ runner.temp }}/hugo_cache
          HUGO_ENVIRONMENT: production
        run: hugo --minify
      - name: Upload artifacts
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./public

  deploy:
    needs: hugo
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
